services:
  web:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://demo:demo@db:5432/demo
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://127.0.0.1:8000/health || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s

  db:
    image: postgres:latest
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "demo", "-d", "demo"]
      interval: 10s
      timeout: 5s
      retries: 5

  wiremock:
    image: rodolpheche/wiremock:latest
    container_name: wiremock
    volumes:
      - ./.devops/wiremock:/home/wiremock
    ports:
      - "8080:8080"
    command:
      - --verbose
      - --global-response-templating

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8088:80
    volumes:
      - ./.devops/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      web:
        condition: service_healthy

volumes:
  db-data:
