services:
  web:
    build:
      context: .
      args:
        ENVIRONMENT: production
    volumes:
      - .:/code
    ports:
      - "9000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
