"""init

Revision ID: 5270bed74746
Revises:
Create Date: 2023-11-22 16:37:20.449234

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "5270bed74746"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CLIENT_ERROR",
                "ACCEPTED_BY_BTOBET",
                "REJECTED_BY_BTOBET",
                "UNKNOWN_BTOBET_STATUS",
                name="status",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "org_account_balance", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("transaction_type", sa.String(length=30), nullable=False),
        sa.Column("mpesa_ref_number", sa.String(length=30), nullable=False),
        sa.Column("mobile_number", sa.String(length=30), nullable=False),
        sa.Column("hashed_mobile_number", sa.Text(), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "update_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payment_id"), "payment", ["id"], unique=False)
    op.create_index(
        op.f("ix_payment_mpesa_ref_number"),
        "payment",
        ["mpesa_ref_number"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_mpesa_ref_number"), table_name="payment")
    op.drop_index(op.f("ix_payment_id"), table_name="payment")
    op.drop_table("payment")
    # ### end Alembic commands ###
